### ISSUE TITLE
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by gaborpapp** [RussTheAerialist/cinderblock-to-cmake#1]
I am trying with the cinder android_linux branch to convert the blocks in the cinder/blocks directory, e.g. OSC.

``` bash
cd blocks/OSC
b2cm .
```

results in the following error:

```
Traceback (most recent call last):
  File "/usr/bin/b2cm", line 9, in <module>
    load_entry_point('b2cm==1.0', 'console_scripts', 'b2cm')()
  File "/usr/lib/python3.4/site-packages/b2cm-1.0-py3.4.egg/b2cm.py", line 144, in main
    tree = etree.parse(resolve_relative_path('cinderblock.xml'))
  File "/usr/lib/python3.4/site-packages/b2cm-1.0-py3.4.egg/b2cm.py", line 36, in resolve_relative_path
    p
  File "/usr/lib64/python3.4/posixpath.py", line 82, in join
    path += b
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

**Comment by graysonarts** [comment]
try using python2.7.  I don't remember if I even tested this on 3.x.  My guess, from quickly looking at the code on github (I'm not at a computer) is because BASE_DIR is a global variable, in the main function near the bottom of b2cm.py, I need to add a "global BASE_DIR" statement at the top of the function.

**Comment by gaborpapp** [comment]
Thanks. Python3 is mentioned in the install section of the readme. With python2.7 I get this:

```
Traceback (most recent call last):
  File "/usr/bin/b2cm", line 9, in <module>
    load_entry_point('b2cm==1.0', 'console_scripts', 'b2cm')()
  File "/usr/lib/python2.7/site-packages/b2cm-1.0-py2.7.egg/b2cm.py", line 144, in main
    tree = etree.parse(resolve_relative_path('cinderblock.xml'))
  File "/usr/lib/python2.7/site-packages/b2cm-1.0-py2.7.egg/b2cm.py", line 36, in resolve_relative_path
    p
  File "/usr/lib64/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by gaborpapp** [comment]
Using python3, adding `global BASE_DIR` to the main function and copying the templates directory to the install folder (/usr/lib/python3.4/site-packages/b2cm-1.0-py3.4.egg/ in my case) has solved it as a workaround.

**Comment by JulieCooper** [comment]
@gaborpapp where within main did you put `global BASE_DIR` ?
